server:
  port: 9092
spring:
  h2:
    console:
      settings:
        trace: false
        web-allow-others: false
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: PAYMENT-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
springdoc:
  swagger-ui:
    enabled: true
payment:
  application:
    display-name: paymentservice
    version: 1.0.0
    component-display-name: payment-service API
    team-mail: venkatagangdhar@gmail.com