server:
  port: 8082
 
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
    client:
      client-id: client
      client-secret: secret
      authorized-grant-types: password